default: &defaults
  push_api_key: <%= ENV['APPSIGNAL_PUSH_API_KEY'] %>

  # Your app's name
  name: "Hanami"
  log_level: trace

development:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true

staging:
  <<: *defaults
  active: true
